name: Build Safari Extension
on:
  push:
    branches:
      - master

jobs:
  macOS:
    name: "MacOS build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Copy configuration
        run: cp config.json.example config.json
      - name: Create Chrome artifacts
        run: npm run build:chrome
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Convert Extension to Safari
        run: xcrun safari-web-extension-converter dist/ --macos-only --project-location ./safari/ --app-name SponsorBlock --no-open
      - name: Build Extension
        run: xcodebuild -project ./safari/SponsorBlock/SponsorBlock.xcodeproj -configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: SponsorBlock-unsigned.app
          path: ./safari/SponsorBlock/build/Release/SponsorBlock.app
